name: cnews-clair_1080p.m3u8

on:
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes
  workflow_dispatch:

permissions:
  contents: write  # Permet au workflow de pousser les modifications dans le dépôt

jobs:
  sync-filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download original cnews-clair-hd.m3u8
        run: |
          curl -o cnews-clair-hd.m3u8 https://raw.githubusercontent.com/Paradise-91/ParaTV/main/streams/canalplus/cnews-clair-hd.m3u8

      - name: Filter cnews-clair-hd.m3u8 content
        run: |
          sed -n '
            /^#EXTM3U/p
            /^#EXT-X-STREAM-INF:.*BANDWIDTH=5364655,/ {
              p
              n
              p
            }
            /^#EXT-X-MEDIA:TYPE=AUDIO,.*GROUP-ID="audio-AACL-96",LANGUAGE="fra"/p
          ' cnews-clair-hd.m3u8 > cnews-clair-hd_1080.m3u8

      - name: Clone target repository (TNT_TV)
        run: |
          git clone https://github.com/WishSmartOTT/TNT_TV.git tnt_tv_repo
          mkdir -p tnt_tv_repo/Streams/France/FHD
    
      - name: Copy filtered file to target repository
        run: |
          cp cnews-clair-hd_1080.m3u8 tnt_tv_repo/Streams/France/FHD/cnews-clair-hd_1080.m3u8
    
      - name: Commit and push changes to TNT_TV
        run: |
          cd tnt_tv_repo
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Streams/France/FHD/cnews-clair-hd_1080.m3u8
          if git diff --cached --quiet; then
            echo "Aucun changement détecté, pas de commit."
            exit 0
          else
            git commit -m "Auto sync and filter cnews-clair-hd_1080.m3u8"
            git push https://x-access-token:${{ secrets.TNT_TV_TOKEN }}@github.com/WishSmartOTT/TNT_TV.git main
          fi
